In [13]:
#Task1
#SuvinaTHapa
#Unit Conversion Program
def convert_units(value, conversion_type):
    """
    This function is used to convetr unit of measurement where the parameter value is the user imput to be conert and conversion)type is type of conversion
    returs :float as converted value


    """
    if conversion_type == "m_to_ft":
        return value * 3.28084

    elif conversion_type == "ft_to_m":
        return value / 3.28084

    elif conversion_type == "kg_to_lbs":
        return value * 2.20462

    elif conversion_type == "lbs_to_kg":
        return value / 0.20462

    elif conversion_type == "l_to_gal":
        return value  * 0.264172

    elif conversion_type == "gal_to_l":
        return value  / 0.264172

    else:
        return None

try:
    print("Choose any conversion to perform:")
    print("1 m_to_ft")
    print("2 ft_to_m")
    print("3 kg_to_lbs")
    print("4 lbs_to_kg")
    print("5 l_to_gal")
    print("6 gal_to_l")

    user_input = input("Enter conversion type: ")
    value = float(input("Enter value:"))
    output = convert_units(value, user_input)
    if output is None:
        print("Enter correct conversion type.")
    else:
        print("Converted value is: ", output)

except ValueError:
    print("Invalid input. PLease enter numeriv value only")

Choose any conversion to perform:
1 m_to_ft
2 ft_to_m
3 kg_to_lbs
4 lbs_to_kg
5 l_to_gal
6 gal_to_l


Enter conversion type:  m_to_ft
Enter value: 8


Converted value is:  26.24672


In [14]:
#Task2
#mathematical operations on List
def find_sum(numbers):
    """
    Calculate the sum of all number user imput
    parameter is numbers whihc is a list of numeric value
    return float: sum of the given number by user
    """
    return sum(numbers)

def find_average(numbers):
    """
    Calculate the average of all number user imput
    parameter is numbers whihc is a list of numeric value
    return float: avergae of the given number by user
    """
    return sum(numbers) / len(numbers)

def find_max(numbers):
    """
    Caluclate the maximun of all number user imput
    parameter is numbers whihc is a list of numeric value
    return float: max of the given number by user
    """
    return max(numbers)

def find_min(numbers):
    """
    Caluclate the minimum of all number user imput
    parameter is numbers whihc is a list of numeric value
    return float: min of the given number by user
    """
    return min(numbers)

#main program
try:
    user_input = input("Enter numbers separated by space: ")
    numbers = list(map(float, user_input.split()))

    if len(numbers) == 0:
        raise ValueError

    print("Choose operation:")
    print("1 Sum")
    print("2 Average")
    print("3 Maximum")
    print("4 Minimum")

    choice = input("Enter which operation to perform: ")

    if choice == "1":
        print("The total sum of the given number is =", find_sum(numbers))

    elif choice == "2":
        print("The total average of the given number is =", find_average(numbers))

    elif choice == "3":
        print("The maximum from the given number is =", find_max(numbers))

    elif choice == "4":
        print("The minimum from the given number is =", find_min(numbers))

    else:
        print("Invalid operation")

except ValueError:
    print("Invalid input")


Enter numbers separated by space:  1 5 7 3 5


Choose operation:
1 Sum
2 Average
3 Maximum
4 Minimum


Enter which operation to perform:  3


The maximum from the given number is = 7.0


In [15]:
#4.2 List Manipulation
#Extracting every other element
def extract_every_other(lst):
    return list[::2]

print(extract_every_elem([1,2,3,4,5,6]))
      

[1, 3, 5]


In [26]:
#Slice SUblist
def get_sublist(lst, start, end):
    return lst[start:end+1]

print("The required slice subset:",get_sublist([1,2,3,4,5,6],2,4))

#Reverse List using SLice
def reverse_list(lst):
   return lst[::-1]
print("The required reverse list with slice:", reverse_list([1,2,3,4,5]))

#Removing first and last num
def remove_first_last(lst):
    return lst[1:-1]
print("the required list after removing first and last number :", remove_first_last([1,2,3,4,5]))

#Get first n Elements
def get_first_n(lst,n):
    return lst[:n]
print("The required first 3 elements  is:", get_first_n([1,2,3,4,5],3))

#Get last n elements
def get_last_n(lst,n):
    return lst[-n:]
print("the required last 2 number is :",get_last_n([1,2,3,4,5],2))

#Reverse skip
def reverse_skip(lst):
    return lst[-2::-2]
print("The reuired reverse skip from second list is:",reverse_skip([1,2,3,4,5,6]))    




The required slice subset: [3, 4, 5]
The required reverse list with slice: [5, 4, 3, 2, 1]
the required list after removing first and last number : [2, 3, 4]
The required first 3 elements  is: [1, 2, 3]
the required last 2 number is : [4, 5]
The reuired reverse skip from second list is: [5, 3, 1]


In [44]:
#4.3 Nested List
#Flatten nested List
def flatten(lst):
    result = []
    for sublist in lst:
        for item in sublist:
            result.append(item)

    return result

print("The required full list from the nested list is :", flatten([[1,2],[3,4],[5]]))


#Accessing the nested eleent
def access_nested_element(lst,indices):
    element = lst
    for i in indices:
        element = element[i]
    return element

lst = [[1,2,3],[4,5,6],[7,8,9]]
print("The required element from the list is:",access_nested_element(lst,[1,2]))

#SUm nisted list
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item,list):
            total += sum_nested(item)
        else:
            total += item
    return total

print("The required sum of nested list is:",sum_nested([[1,2],[3,[4,5]],6]))


#Remove element
def remove_element(lst,elem):
    result = []
    for item in lst:
        if isinstance(item,list):
            result.append(remove_element(item,elem))
        else:
            if item != elem:
                result.append(item)
    return result
print("The output after removing elemnt 2 from the list is:",(remove_element([[1,2],[3,2],[4,5]],2)))

#Finding Maximum
def find_max(lst):
    max_val = float('-inf')
    for item in lst:
        if isinstance(item,list):
            max_val = max(max_val,find_max(item))
        else:
            max_val = max(max_val,item)
    return max_val
print("The required maximun number from the list is:",find_max([[1,2],[3,[4,5]],6]))

#Count occurance
def count_occurrences(lst,elem):
    count = 0
    for item in lst:
        if isinstance(item,list):
            count += count_occurrences(item,elem)
        else:
            if item == elem:
                count += 1
    return count
print("the required occurance of the number 2 is:",count_occurrences([[1,2],[2,3],[2,4]],2))


#deep flatten
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item,list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result
print("The required single list from many nested list is:",(deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]])))



#Avrage mested
def average_nested(lst):
    flat = deep_flatten(lst)
    return sum(flat)/len(flat)
print("The avergae from the nested list is:",average_nested([[1,2],[3,4],[5,6]]))







The required full list from the nested list is : [1, 2, 3, 4, 5]
The required element from the list is: 6
The required sum of nested list is: 21
The output after removing elemnt 2 from the list is: [[1], [3], [4, 5]]
The required maximun number from the list is: 6
the required occurance of the number 2 is: 3
The required single list from many nested list is: [1, 2, 3, 4, 5, 6, 7, 8]
The avergae from the nested list is: 3.5


In [54]:
#10 NumPy Tasks
#10.1 Basic Vector and Matrix Operation with Numpy.
#Problem - 1: Array Creation:
import numpy as np
#initialize empty array
a = np.empty((2,2))
print("The required empty array is:\n",a)

#2. All one arrray(4x2)
b = np.ones((4,2))
print("The required 4 x 2 array is:\n",b)

#3. Array filled wit a value(np.full)
c = np.full((3,3), 5)
print("The required 3x3 array wuth value is:\n",c)


#4. Zeros with same shape as question 3 
d = np.zeros_like(c)
print("The required 3x3 array with value as 0:\n",d)


#5. Ones with same shape
e = np.ones_like(c)
print("The required 3x3 array with value 1 is:\n", e)


#6. Converting lis to numpy array
new_list = [1,2,3,4]
arr = np.array(new_list)
print("The list after converting to numpy array is:\n", arr)


The required empty array is:
 [[1.14323354e+243 8.27547638e+242]
 [9.47779021e-311 3.96236456e-133]]
The required 4 x 2 array is:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
The required 3x3 array wuth value is:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
The required 3x3 array with value as 0:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
The required 3x3 array with value 1 is:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
The list after converting to numpy array is:
 [1 2 3 4]


In [75]:
#Probem 2 - Array Manipulation
#1. Array from 10 to 49
arr = np.arange(10,50)
print("The required array after manipulation:\n",arr)

#2.  3x3 matrix from 0 to 8
matrix = np.arange(9).reshape(3,3)
print("\nThe required 3x3 matrix from 0 to 8 is:\n", matrix)


#3.  Identity Matrix
identity = np.eye(3)
print("\nThe required identity matrix is:\n", identity)


#4. Random array of size 30
arr = np.random.random(30)
print("\nThe required total 30 array matrix:\n", arr)
print("Total Mean:", arr.mean())


#5.  Random 10x 10 matrix + min and max
arr = np.random.random((10,10))
print("\nMaximum:", arr.min())
print("\nMinimum:", arr.max())



#6. Zero array size 10 and replacing 5th element
arr = np.zeros(10)
arr[4] = 1
print("\nThe required zero aaray while replacing 5th with 1:",arr)


#7. Reverse array
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
print("\nThe reversed array is :\n", reversed_arr)




#8. 2D array with border=1 and inside=0
arr = np.ones((5,5))
arr[1:-1, 1:-1] = 0
print("\nThe 2D array with border 1 and inside 0 is :\n", arr)


#9. Checkboard Pattern with 8x8
checker = np.zeros((8,8), dtype=int)
checker[::2, 1::2] = 1
checker[1::2, ::2] = 1
print("\nThe required checkboard pattern matrix of 8x8 size :\n", checker)





The required array after manipulation:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

The required 3x3 matrix from 0 to 8 is:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

The required identity matrix is:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

The required total 30 array matrix:
 [0.00449726 0.89069308 0.374502   0.32330723 0.78960857 0.32495048
 0.3327878  0.86623438 0.79464249 0.23577721 0.87392189 0.48173313
 0.16358932 0.78875546 0.28433569 0.34034047 0.55597816 0.66328459
 0.84725371 0.3657003  0.87027053 0.76451917 0.91702088 0.34034344
 0.34455241 0.21099283 0.52360556 0.53520008 0.4899382  0.62395389]
Total Mean: 0.5307430064714976

Maximum: 0.005416964315366424

Minimum: 0.9982711542492075

The required zero aaray while replacing 5th with 1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

The reversed array is :
 [0 4 0 0 2 1]

The 2D array with border 1 and inside 0 is :
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1.

In [90]:
#Probem 3 Array Operations
#Add arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print("The array after adding x and y matrix is:\n", x+y)

#Subtrat array
print("\nThe array after subtracting x and y matrix is:\n", x-y)

#multiply by integer
print("\nThe array after multiplying x and 3 matrix is:\n", x*3)

#Square each element
print("\nThe array after squaring each element is:\n", x**2)

#Dot Products
print("The array after applying dot products between v and w is:", np.dot(v,w))
print("\nThe array after applying dot products between x and v is:\n", np.dot(x,v))
print("\nThe array after applying dot products between x and y is:\n", np.dot(x,y))


#Concate arrays
#row concatenate array
row_concat = np.concatenate((x,y), axis=0)
print("\n Row concatenate of x and y:\n", row_concat)

#column concate
col_concat = np.column_stack((v,w))
print("\nThe column concatenation of v and w:\n", col_concat)


#Concatenate x and v
try:
    x_v_concat = np.concatenate((x,v))
    print("\n The concatenate of x and v is:\n", x_v_concat)

except ValueError as e:
    print("\n The concate between x and v cannot be done. As the x and v do not have same number of dimension to concate")








The array after adding x and y matrix is:
 [[ 6  8]
 [10 13]]

The array after subtracting x and y matrix is:
 [[-4 -4]
 [-4 -3]]

The array after multiplying x and 3 matrix is:
 [[ 3  6]
 [ 9 15]]

The array after squaring each element is:
 [[ 1  4]
 [ 9 25]]
The array after applying dot products between v and w is: 219

The array after applying dot products between x and v is:
 [29 77]

The array after applying dot products between x and y is:
 [[19 22]
 [50 58]]

 Row concatenate of x and y:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

The column concatenation of v and w:
 [[ 9 11]
 [10 12]]

 The concate between x and v cannot be done. As the x and v do not have same number of dimension to concate


In [109]:
#Probem 4 - Matrix Operations
#1. Prove A·A⁻¹ = I
A = np.array([[3, 4],[7, 8]])
A_inv = np.linalg.inv(A)
I = np.dot(A,A_inv)
print("The required inverse matrix is:\n", np.round(I))


#2.  Prove AB ≠ BA
B = np.array([[5,3],[2,1]])
AB = np.dot(A,B)
BA = np.dot(B,A)
print("\nAB =\n", AB)
print("BA =\n", BA)
print("AB is not equal to BA")


#3. Prove (AB)ᵀ = BᵀAᵀ
left = np.dot(A,B).T
right = np.dot(B.T,A.T)
print("\nLeft side (AB)^T is:\n", left)
print("Right side (B^T x A^T) is:\n", right)
print("Both left and right side is commutative and equal")



#Linear Equations
A = np.array([
[2,-3,1],
[1,-1,2],
[3,1,-1]
])

B = np.array([-1,-3,9])
A_inv = np.linalg.inv(A)

X = np.dot(A_inv,B)

print(X)
#using Numpy linear solver
solution = np.linalg.solve(A,B)

print("\nSolution using numoy solver:",solution)






The required inverse matrix is:
 [[1. 0.]
 [0. 1.]]

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
AB is not equal to BA

Left side (AB)^T is:
 [[23 51]
 [13 29]]
Right side (B^T x A^T) is:
 [[23 51]
 [13 29]]
Both left and right side is commutative and equal
[ 2.  1. -2.]

Solution using numoy solver: [ 2.  1. -2.]


In [122]:
#10.2 Experiment 
import numpy as np
import time
#Element wise Addition
#python
size = 1000000
list1 = list(range(size))
list2 = list(range(size))
start = time.time()
result = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print("Time taken using Python lists for addition:", end - start, "seconds")
#Nump ARray
arr1 = np.arange(size)
arr2 = np.arange(size)
start = time.time()
result = arr1 + arr2
end = time.time()
print("Time taken using NumPy for addition:", end - start, "seconds")


#Element wise Mu;tiplication
#python
start = time.time()
result = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print("\nTime taken using Python lists for multipication:", end - start, "seconds")
#Numpy Array
start = time.time()
result = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print("Time taken using Python lists for multiplication:", end - start, "seconds")


#Dot product
#Python
start = time.time()
dot = sum(list1[i] * list2[i] for i in range(size))
end = time.time()
print("\nDot product:", dot)
print("Time using Python lists for dot product:", end - start, "seconds")
#Numpy
start = time.time()
dot = np.dot(arr1, arr2)
end = time.time()
print("\nDot product:", dot)
print("Time using NumPy for dot product:", end - start, "seconds")


#Matrix multiplication
#Python List
size = 1000
A = [[i for i in range(size)] for j in range(size)]
B = [[i for i in range(size)] for j in range(size)]
result = [[0]*size for _ in range(size)]
start = time.time()
for i in range(size):
    for j in range(size):
        for k in range(size):
            result[i][j] += A[i][k] * B[k][j]
end = time.time()
print("\nTime using Python lists for matrix multiplication:", end - start, "seconds")

#Numpy
size = 1000
A = np.random.rand(size, size)
B = np.random.rand(size, size)
start = time.time()
result = np.dot(A, B)
end = time.time()
print("Time using NumPy for matrix multiplication:", end - start, "seconds")









Time taken using Python lists for addition: 0.11962723731994629 seconds
Time taken using NumPy for addition: 0.020998716354370117 seconds

Time taken using Python lists for multipication: 0.11985921859741211 seconds
Time taken using Python lists for multiplication: 0.1410813331604004 seconds

Dot product: 333332833333500000
Time using Python lists for dot product: 0.11459016799926758 seconds

Dot product: 584144992
Time using NumPy for dot product: 0.0019986629486083984 seconds

Time using Python lists for matrix multiplication: 180.84415745735168 seconds
Time using NumPy for matrix multiplication: 0.03299856185913086 seconds
